project:
  type: website

website:
  title: "OT WIKI"
  site-url: https://otwiki.github.io/otwiki-main/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true

editor: visual

